### ISSUE TITLE
Local docs

### ISSUE THREAD

**Issue by qinohe** [opnsense/docs#115]
Hi guys, don't know if it's me or it's the docs, but, in the online docs (wiki.opnsense.org) I can search for an item the results are in the right frame. 
However, when I compile the docs locally I'm not able to perform a search, the 'wheel' keeps running nothing happens.
Now just as a check I didn't miss any library or other piece of software in the docs or on my server, I compiled the Pfsense wiki, put it on my local server and checked if the search function works and it does.

It could still be I'm missing something or this is already know, but I didn't find relevant info.
Thanks again for this beautiful OS, mark

**Comment by AdSchellevis** [comment]
It's not likely the docs, we upload on regular bases leading to the state you see online. We don't offer support on sphinx and it's plugins.

**Comment by qinohe** [comment]
You think it's sphinx or one of the plugins?
Hmmz, I'm running in a clean chroot(systemd-nspawn) running ArchLinux,everything is pretty 'fresh' there;)

I will try see if I can figure it out, though, from your reaction I guess you don't see my problem on a local! server! Here it is running on Debian stable btw...

**Comment by qinohe** [comment]
Well the problem was on this side, after rebuilding the chroot and rebuilding the docs all went fine.

I still have the old chroot and will have a look at it, my guess is some package didn't get updated..
Thanks
