### ISSUE TITLE
Build errors in IPsec road warrior files; some duplication

### ISSUE THREAD

**Issue by MichaelDeciso** [opnsense/docs#154]
When building the documentation, there are some build errors in the ipsec-rw*.rst files. Additonally, both ipsec-road.rst and ipsec-rw.rst exist, and both are about the same subject.

@mimugmail was the last person to work on it, and it appears to a work in progress. For this reason, I haven't yet touched these files, but I'd like @mimugmail to tell me what the plans are.

**Comment by mimugmail** [comment]
@MichaelDeciso the -rw* files are not yet linked to the official docs ... I need to add sections for iPhone and macOS. ATM I already have stuff fro iPhone but not yet found the time.

What are the complains when building docs?

**Comment by MichaelDeciso** [comment]
```
 /Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-android.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-linux.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eapradius.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eaptls.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-ikev1xauth.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-mschapv2.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-rsamschapv2.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-w7.rst: WARNING: document isn't included in any toctree
```

Do I understand correctly that `ipsec_road.rst` will go away and that `ipsec_rw.rst` will take its place once you're finished?

**Comment by mimugmail** [comment]
This was my thinking but we can rename after replacement If it would lead into trouble regarding Google searches etc.

**Comment by MichaelDeciso** [comment]
That sounds like a good idea.

When the ipsec_rw* docs are finished, the build errors should go away as well (or change, at least), so I'll just leave the files as-is for now.
