### ISSUE TITLE
DnsCrypt missing API docs

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/docs#170]
I am trying to find figure out how to call the API for DnsCrypt but so far from looking at the code no dice.
Can the missing Documentation for the API for this be added please? TIA

CC @mimugmail

**Comment by mimugmail** [comment]
Have a look at Bind Plugin. Should be similar

**Comment by L1ghtn1ng** [comment]
I have had a look at it and that is missing docs for the API as well and cannot figure it out from the code either. @fichtner @AdSchellevis I think it would be a good idea going forward that when new plugins get created that they have to have docs for it plus API examples before it gets merge as a contributing guide line, thoughts?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng @fvanroie has made a powershell script (https://github.com/fvanroie/opnsense_MakeDocs) some time ago, which is where most existing come from as well (https://github.com/opnsense/docs/pull/24). If someone has time to convert it to python, we might consider adding it to our usual workflow.  You should be able to generate similar docs with the his tool in the mean time for your own purposes.

**Comment by fvanroie** [comment]
@AdSchellevis You can assign this one to me, I'll have a look at running/updating the scripts.

**Comment by AdSchellevis** [comment]
@fvanroie done, thanks in advance!
