### ISSUE TITLE
"one physical machine as master and a second machine as slave"

### ISSUE THREAD

**Issue by hboetes** [opnsense/docs#176]
This sentence from the carp how-to contains a thinko I think.

> When using different network drivers on both machines, like running a HA setup with one physical machine as master and a second machine as slave, states can not be synced as interface names differ. The only workaround would be to set up a LAGG.

I think this edit would fix it: `s|second|virtual|`

**Comment by mimugmail** [comment]
Just edit the file and it's done :) Thanks

**Comment by hboetes** [comment]
Ah, yes. pull requests are a lot easier these days.

**Comment by fichtner** [comment]
https://github.com/opnsense/docs/pull/178
