### ISSUE TITLE
Cloud Import users button missing for LDAP

### ISSUE THREAD

**Issue by rudiservo** [opnsense/docs#201]
The Cloud import button is missing after I added LDAP server (Zentyal, I can communicate with it):

Also I got this error, is it linked somehow?

`[07-Oct-2019 16:24:01 Atlantic/Azores] PHP Warning: implode(): Invalid arguments passed in /usr/local/www/system_authservers.php on line 249`

I have the system upgrade since 17.0

Currently:
OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s  28 May 2019

**Comment by fichtner** [comment]
Implodes() issue should be fixed on master, see https://github.com/opnsense/core/commit/09c34b272

**Comment by rudiservo** [comment]
@fichtner Cool Thanks, how do I fix the manual BTW?

**Comment by fichtner** [comment]
You can clone this docs git to your own profile and edit the docs file online, commit and issue a PR. We will fix it in the midterm, but always happy about short term help. :)
