### ISSUE TITLE
(Broken Link) Legal Notices - Packages and ports

### ISSUE THREAD

**Issue by nekoprog** [opnsense/docs#205]
I found a broken link (404 error) [here](https://github.com/opnsense/docs/blob/master/source/legal.rst#L67). Hope to see this link updated.

**Comment by AdSchellevis** [comment]
that's on old one it seems https://github.com/opnsense/tools/commit/acda787d377fcf30c5b2abf4578726009fa8f605, we should probably remove the link and point to the file textually (since we don't want to point to a specific version)

**Comment by nekoprog** [comment]
Very old indeed.
