### ISSUE TITLE
Update link to AV Test file

### ISSUE THREAD

**Issue by dpieski** [opnsense/docs#206]
Test AV setup page: https://docs.opnsense.org/manual/how-tos/proxyicapantivirusinternal.html

The link is broken to the EICAR AV test file. 
Old link: http://www.eicar.org/85-0-Download.html

Two alternatives. 
Archive version, new location: http://2016.eicar.org/85-0-Download.html
New Version location: https://www.eicar.org/?page_id=3950

Presumably, both provide the same file. The site was rebuilt. The old site is at the 2016 subdomain.

**Comment by AdSchellevis** [comment]
for the example, it should likely be the first one as being served over http. Can you open a PR fr it? thanks in advance.

**Comment by dpieski** [comment]
Why should it be the first one? Why does it matter if the webpage is http or https?
