### ISSUE TITLE
Add documentation for the expected JSON data structure for API endpoints

### ISSUE THREAD

**Issue by michlschmid** [opnsense/docs#214]
I tried to get started with the OpnSense API following the given docs:
* https://docs.opnsense.org/development/api/core/ids.html
* https://docs.opnsense.org/development/how-tos/api.html

Connecting and interacting with the API works well so far.

As my goal is "adding custom IDS/IPS rules" to the process I tried doing
so via the following endpoint:
`POST` `https://my-opnsense/api/ids/settings/adduserrule`

What I'm missing is the expected data format of the JSON object
used within the POST that describes my actual rule.

Striving through the docs I've not seen any description of POST
values or examples. I would love to see this as an enhancement
for easing the learning curve of the API.

;-)

**Comment by AdSchellevis** [comment]
For easy validation of the required settings for a specific endpoint, you best use the network inspector of your browser (the UI pages use the same ones).

We're not planning to document all endpoints beyond the level of their existence at the moment.
(there's no schema underneath, which makes it impossible to automate this)
