### ISSUE TITLE
How-To for clamav is a bit too brief, how does clamav work?

### ISSUE THREAD

**Issue by sjjh** [opnsense/docs#222]
After reading the how to for clamav ( docs/source/manual/how-tos/clamav.rst) ist's unclear to me if the plugin works on its own or if the proxy and c-icap needs to be enabled in addition to make any use of clamav. It would be good to expand a little on how clamav works (on its own) and what it does, or which other plugins (c-icap & web proxy?) need to be used together with clamav to make any use of it.

**Comment by mimugmail** [comment]
Clamav is just what it is, every plugin capable to use it can speak with it. Currently cicap and rspamd
