### ISSUE TITLE
ipsec: xauth correction

### ISSUE THREAD

**Issue by fichtner** [opnsense/docs#23]
https://forum.opnsense.org/index.php?topic=7816.0

**Comment by dartmann** [comment]
Hi, ich bin beim Einrichten einer IPsec Road-Warrior Konfiguration auf dieses Ticket [gestoßen](https://forum.opnsense.org/index.php?topic=7816.0) während meiner Recherchen.
Wird das noch im zugehörigen [OPNsense Wiki-Artikel](https://docs.opnsense.org/manual/how-tos/ipsec-road.html) ergänzt?
Vielen Dank 👍

**Comment by mimugmail** [comment]
I'll rewrite the Road Warrior setup in a few days since there will come more changes than this.

**Comment by dartmann** [comment]
> I'll rewrite the Road Warrior setup in a few days since there will come more changes than this.

Super, thank you.

**Comment by AdSchellevis** [comment]
@mimugmail, @fichtner was this also taken care of? the issue looks stale to me.

**Comment by fichtner** [comment]
Fixed in c6f3fa2e91
