### ISSUE TITLE
No mention of required plugins on doc pages

### ISSUE THREAD

**Issue by darkain** [opnsense/docs#25]
I was looking into dynamic routing, and there is absolutely no mention whatsoever that a plugin is required for this feature (which I expected would require a plugin). Additionally, figuring out which plugin also look far too much work to figure out, too. The docs should be updated to list required plugins on their various configuration documentation pages. 

Examples:
https://wiki.opnsense.org/manual/how-tos/dynamicrouting_ospf.html
https://wiki.opnsense.org/manual/how-tos/dynamicrouting_howto.html

**Comment by fabianfrz** [comment]
are you sure?
https://wiki.opnsense.org/manual/dynamic_routing.html

**Comment by darkain** [comment]
When entering the docs from an external source (Google) going to the direct pages listed, there is no mention of where to start. It just goes straight into configuring the given service. There should at least be a back-link to the first page of the "howto". This leads to user confusion of what appears at first as missing features.

**Comment by AdSchellevis** [comment]
timeout  (more info https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
