### ISSUE TITLE
How to complete WireGuard Site-to-Site Setup?

### ISSUE THREAD

**Issue by duncanwebb** [opnsense/docs#268]
Before you ask a new question, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

The documentation for a [WireGuard Site-to-Site Setup](https://docs.opnsense.org/manual/how-tos/wireguard-s2s.html) is rather terse and simply doesn't work.

The setup defined allows the two OpnSense hosts to create a VPN link between themselves, this is easy to do and there are many examples about to help. The two hosts can talk together but behaves like a road warrior configuration and not a site-to-site configuration.

A site-to-site VPN means that hosts behind the OpnSense firewall can talk to hosts behind the other OpnSense firewall. The documentation does not show how to do this. OpenVPN site-to-site does work as expected.

I have tried searching and asking question on the forum for some information about site-to-site. 

My question is does WireGuard site-to-site work and if so could some update the wiki page with a working example?

Thanks for a great product and looking forward to some updated documentation.

**Comment by mimugmail** [comment]
Where did you fail? On Site A set in endpoint network of B and vice versa, thats it.

Please post forum link and close this one here.

**Comment by duncanwebb** [comment]
[WireGuard VPN Site-to-Site question](https://forum.opnsense.org/index.php?topic=17836.0)

Let's say that site A is the office and site B is home. Then I would like to reach the site A host from one or more host in site B.

If we can get this to work then I'd be delighted and would gladly write the steps as an MD document and with images so that you could review the steps and, if it pleases you, update the wiki.

If you are happy with this then would you leave the ticket open until then?
