### ISSUE TITLE
Fuzziness in source/manual/how-tos/lan_bridge.rst

### ISSUE THREAD

**Issue by spiriapbergeron** [opnsense/docs#285]
Hi. First, thanks a million for this howto. It saved a ton of time and screwing around.

I do see this readme being used by the official opnsense documentation also!
https://wiki.opnsense.org/manual/how-tos/lan_bridge.html

In general the instructions are quite clear, but the last step I'm unsure about. 

For Step 6, you state:

_Go to System->Settings->Tunables and **select** using the pen button net.link.bridge.pfil_member and set the value to 0._

and

**Select** the tunable net.link.bridge.pfil_bridge and set the value to 1

But on my current opnsense version, these two variables do not exist.  
So, if the variables don't exist, should we add them (I did).

So I guess the fuzziness is around the word "select" or "create if they don't exist" or something.

Thanks for the howto!

**Comment by AdSchellevis** [comment]
we do ship it by default, but I don't mind adding a small comment inline as well.
https://github.com/opnsense/core/blob/0b379917aecaa3cad23d1fae9514997563d63cee/src/etc/config.xml.sample#L112-L116

**Comment by spiriapbergeron** [comment]
I had never heard of these variables until I read your howto -- and I can say for certain I didn't delete them somehow, and they definitely weren't part of my installation. Very weird.
