### ISSUE TITLE
More forecoming handling of new issues than with current OPNsense-bot

### ISSUE THREAD

**Issue by cluck** [opnsense/docs#334]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [*] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Despite covering the questions in the template, the OPNsense-bot chimed in, deciding that the report was low priority, "because" the template was not followed; what the bot actually detected (probably) was that some placeholder text of the template was not in place anymore.

This lead to a wrong, rude and unnecessary confrontation.

Moreover, it leads to a degraded experience with future issues I might submit and that will eventually become part of the knowledge base of known issues. Many issues at hand are already verbose, repetitive, un-concise, and thus unpleasant and cumbersome to read, because of that boilerplate. 

**Describe the solution you like**

Mark removable placeholder text as such, or add a notice to please keep all of it.

Maybe, establish a policy, and mention it in the template, that the description of the ticket shall be compacted *after* triaging and the problem is understood and acknowledged by others.

Change the template so that it states the existence of the bot and what it will do. Maybe describe it in the contributing document too.

**Describe alternatives you considered**

Accept the perceived gap of 3-4 years between "marketing" and "code reality" of this project and take a look at it when the next generation of firewalls is due.

Stop investing time in the OPNsense project.

**Additional context**

https://github.com/opnsense/docs/issues/331#issuecomment-831265185
https://github.com/opnsense/docs/issues/332#issuecomment-831265175

**Comment by AdSchellevis** [comment]
Hi @cluck ,

Although there's always room for improvements, the tone and context in your tickets don't really invite people to work out solution for issues you seem to have. 

As with many projects it's hard to keep up with documentation, quite some people try to invest the time they can spare helping out and improve different areas of our eco system. It's not perfect, but getting better with every release. 

When being invited to contribute into an area of our eco system for a simple fix (https://github.com/opnsense/core/issues/2173#issuecomment-831248461), your response seems to be to complain in general terms (which isn't very constructive).

If your intend is to spend time on (and with) the project, I can only advice to be the change you wish to see... It may encourage others to work with you.

Best regards,

Ad
