### ISSUE TITLE
Squid - Missing information how to use  "squid configuration directives"

### ISSUE THREAD

**Issue by upended** [opnsense/docs#339]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**
Squid has over 100 (I'm guessing) options which have their own settings specification (See image below for a few of them).  In the opnsense web proxy documentation, there is no mention of these configurations, nor how they can be used within the system.  From what I can see, opnsense has simplified the directives into different areas.  However, users such as myself are not able to decipher which directives are being used based off opnsense labeling.  And, in situations where a user want to add an additional directive not covered by opnsense interface, there is no documentation available to show how to use these additional directives which are not listed in the FW webpages.

![image](https://user-images.githubusercontent.com/63566363/118437176-00858780-b697-11eb-8da3-f453bd03bf63.png)
  

**Suggestions**
If documentation can be added as to which directives are already in place within the current webpages, and what additional steps (if any) are needed to utilize the directive beyond what options are given within the FW webpages.

Example:
On Services: Web Proxy: Administration: ACL, Multiple options are giving such as allowed subnets, blacklist, allowed destination tcp port.  In the squid documentation, files can be used (refer to image below).  If I wanted to use a file, how can I do so with the current interface?

![image](https://user-images.githubusercontent.com/63566363/118440043-ed28eb00-b69b-11eb-8892-8aa5d3a7e889.png)

**Version affected**

Which version of the software are you using?
(e.g. OPNsense 21.1)

**Describe alternatives you considered**

At the very least, would it be possible to add in the documentation a chart indicating / listing... 

check_hostnames = ?
htcp_port   = ?
icp_port      = icp port
ignore_unknown_nameservers = ?

Also, include how a squid configuration directive not included in Services: Web Proxy: Administration webpages, can be added by the user manually.  

**Additional context**

**Comment by AdSchellevis** [comment]
I'm not sure how one should fit that in logically, to be honest, haven't seen other vendors doing something similar either. Not all settings correlate one to one and most of them have defaults when not set. 

You could always open a PR with a proposal. We're open for idea's that help explain functionality better, just try to keep maintenance in mind as well as the less technical user.
