### ISSUE TITLE
Multiple public ips on one modem

### ISSUE THREAD

**Issue by freddykromer** [opnsense/docs#397]
We added four public IPs to our connection. Before that we just had one. 
We wanted to build a separated network on one of the new public IPs with it's own opnsense.
For the outside everything works fine but we can't reach the new network from the existing one.
In both firewall logs you can see that the request is allowed but pings are not working and websites are not reachable.
So the two opnsense are not reachable from each other.
Can someone help with this problem?

**Comment by AdSchellevis** [comment]
best use our forum, which is available at https://forum.opnsense.org
