### ISSUE TITLE
ip range

### ISSUE THREAD

**Issue by shreyasajj** [opnsense/docs#400]
In the docs yall said that `10.0.0.1-10.0.0.10` would work under aliases for host's but it did not. Have I dont something wrong. Thanks 
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**

A clear and concise description of what the issue is, where in the documentation did you find it.
(e.g. on https://docs.opnsense.org/intro.html I've missed some context around ... )

**Suggestions**

Provide suggestions in howto improve the paragraph or chapter in question.
(e.g. could be a simple typo or an explanation how a (part of) the text can be improved)

**Version affected**

Which version of the software are you using?
(e.g. OPNsense 21.1)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Additional context**

**Comment by shreyasajj** [comment]
https://github.com/opnsense/docs/issues/342 this change but I got Entry "10.0.0.1-10.0.0.10" is not a valid hostname or IP address.

**Comment by fichtner** [comment]
Will he fixed in 22.1.7.
