### ISSUE TITLE
IPSec phase 2 instructions are incorrect/outdated

### ISSUE THREAD

**Issue by joewesch** [opnsense/docs#403]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**

On the documentation page for creating an IPSec tunnel, for [Step 2](https://docs.opnsense.org/manual/how-tos/ipsec-s2s.html#step-2-phase-2-site-a) and [Step 4](https://docs.opnsense.org/manual/how-tos/ipsec-s2s.html#step-4-phase-2-site-b) the instructions state to add a Phase 2 configuration by clicking on the `+` icon to the right of the empty list. There is, however, no `+` icon on this empty list on the latest version of OPNSense.

**Suggestions**

It seem now you need to click on the `+` icon on the right side of the **Phase 1 configuration** you made in the previous step instead to add a Phase 2 configuration for that specific peer.

**Version affected**

22.1.7

**Describe alternatives you considered**

None

**Additional context**

None

**Comment by AdSchellevis** [comment]
@joewesch thanks for reporting. fixed in https://github.com/opnsense/docs/commit/9076705a575783ff289ed572c603c5780395d769
