### ISSUE TITLE
KVM "q35" hardware type works fine on 22.1.x

### ISSUE THREAD

**Issue by ZPrimed** [opnsense/docs#414]
### Important notices

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

### Describe the issue

https://docs.opnsense.org/manual/virtuals.html#kvm

Documentation says that the KVM / QEMU "q35" hardware type doesn't work, but this is incorrect as of 22.1.x with the FreeBSD 13.x base. I've been running a virtual installation on top of ProxmoxVE for a few weeks and it seems to work fine. I am using virtio storage, plus PCI(e)-passthrough of 3 NICs as well as a virtio NIC.

### Suggestions

> **Q35 chipset** OPNsense on KVM currently does not work with the Q35 chipset. Virtio and other PCIe devices do not get detected properly. This is a FreeBSD/KVM related [issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236922) that is unspecific to OPNsense.

Change to:
**Q35 chipset**  As of 22.1.x, OPNsense is based on FreeBSD 13.0, which includes support for the virtualized Q35 chipset and newer generation of KVM `virtio` devices. Note that this was a relatively recent addition to FreeBSD, so it may not be as well tested as the i440 support. 

### Version affected

OPNsense 22.1.x (currently 22.1.9_1)

### Describe alternatives you considered
n/a

### Additional context
n/a

**Comment by AdSchellevis** [comment]
@ZPrimed thanks! Changed it as suggested
