### ISSUE TITLE
Update Unbound->Overrides documentation

### ISSUE THREAD

**Issue by swhite2** [opnsense/docs#418]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Unbound -> Overrides is changing a bit so it would make sense to keep this up-to-date in the documentation. It isn't very well documented in general so an elaboration here is fitting.

Things to consider:
- How PTR records are generated.
- Clearly describe how system A/AAAA records can be manipulated.
- Hint that domain overrides shouldn't really be used for it's functionality as it functions completely different from a Host Override, instead refer to the Query Forwarding page.

**Comment by swhite2** [comment]
Done in https://github.com/opnsense/docs/commit/a67e130d238b89f863ab2f7ef83e7253d0ad1412.

@fichtner Parking it here until the mentioned items are in release:

- DNSSEC + rebinding update: https://github.com/opnsense/core/commit/f3efe39f7b7e182bb77a7dd3a371fe4c5c054585
- A/AAAA/PTR records: https://github.com/opnsense/core/commit/92a5a224dd3d08df822cbe722ba5657db1ac7991

**Comment by fichtner** [comment]
Just for completeness from roadmap discussion: overrides and query forwarding are the same thing according to the forum https://forum.opnsense.org/index.php?topic=29813.0

**Comment by swhite2** [comment]
This was completed with https://github.com/opnsense/docs/commit/1b888f7233bfde1b96411abbc470196a09fde21f
