### ISSUE TITLE
add some captions to the HelloWorld documentation 

### ISSUE THREAD

**Issue by KDGundermann** [opnsense/docs#423]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

add some captions to the HelloWorld documentation

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/docs/pull/426
