### ISSUE TITLE
API documentation missing crucial information regarding additional packages required

### ISSUE THREAD

**Issue by wrobelda** [opnsense/docs#436]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**

I spent about an hour trying to figure out why the examples from https://docs.opnsense.org/development/api/plugins/firewall.html didn't work on my end with:

```
{"message":"controller OPNsense\\Firewall\\Api\\FilterController not found","status":400}%
```

Since there are many variables involved, e.g. the client used, the query itself, the permissions (authentication and authorization), I spent over an hour figuring it out, until I stumbled upon an information regarding the `os-firewall` firmware package that actually provides the API endpoints listed on that page.

I found absolutely no mentioning of that anywhere in the documentation, which is extremely misleading and frustrating. 

**Suggestions**

Update API documentation, explain which APIs require which additional packages to be installed.

**Version affected**
 22.7.8

**Comment by kulikov-a** [comment]
sorry, but the link you provided starts with:
"The **firewall API plugin** is a first step into migrating the legacy firewall components from OPNsense, although it does contain a user interface, it’s main focus is only to provide machine to machine interaction between custom applications and OPNsense for selected features." ?

**Comment by wrobelda** [comment]
OK, but that's still very vague, even to an English speaker. That's because this page is already in the "Plugins API" section, which could indicates that the plugins come with their own API. In reality, however, ąt least the firewall plugin requires *an additional* plugin for the API to work. 

Just rephrasing that into:

_"The firewall plugin requires a separate API plugin ('os-firewall'), which is a first step into migrating (...)"_ 

would help tremendously.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/docs/commit/45e1b74f369ccd49493fb830c78526dd8b2cb12e
