### ISSUE TITLE
Adding NAT Reflection knowledge to docs

### ISSUE THREAD

**Issue by Monviech** [opnsense/docs#486]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

I would like to convert my opinionated NAT Reflection tutorial into a technical how-to doc article.
https://forum.opnsense.org/index.php?topic=34925.0

I would like to know the following things before starting any work on it:
- Is this wanted or needed in the documentation?
- There are different methods described in my tutorial. Should the focus be on the manual or automatic implementation of NAT Reflection? A doc article like this could guide users to a prefered method that fits into the roadmap of opnsense - For example reducing automatic rules.

Thank you for any input.

**Comment by AdSchellevis** [comment]
I certainly think it's a good idea to extend the ANT documentation, only challenge is how it should integrate into the existing document (https://docs.opnsense.org/manual/nat.html). I don't mind reviewing and offering feedback if you are willing to spend time on improving the document.

**Comment by Monviech** [comment]
Okay, I will work on adding a how-to section for manual nat reflection rules into the docs. I found this where it states that the automatic rules are indeed legacy: https://docs.opnsense.org/manual/firewall_settings.html#network-address-translation

**Comment by Monviech** [comment]
https://github.com/opnsense/docs/pull/489
