### ISSUE TITLE
Update terminology in Wireguard pages 

### ISSUE THREAD

**Issue by satrapes** [opnsense/docs#515]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ *] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [* ] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**
Documentation for some of the Wireguard pages in https://docs.opnsense.org/plugins.html#vpn-connectivity have not been updated with the new tab terminology.
https://docs.opnsense.org/manual/how-tos/wireguard-client.html
https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html
https://docs.opnsense.org/manual/how-tos/wireguard-client-azire.html
https://docs.opnsense.org/manual/how-tos/wireguard-client-mullvad.html

**Suggestions**

Replace Local references with Instances and Endpoints with Peers and maybe more.

**Version affected**
Documentation version bcb0368

**Describe alternatives you considered**

N/A

**Additional context**
N/A

**Comment by AdSchellevis** [comment]
If I'm not mistaken, the examples have recently been refactored, the new documentation and terminology can be found here https://docs.opnsense.org/manual/vpnet.html#wireguard

When missing some references, just open a PR.

**Comment by satrapes** [comment]
Hi @AdSchellevis. I have spotted that it has been updated. I meant that it hasn't been propagated to the how-to pages. I will try and do it myself. You will find a PR soon. Thanks
