### ISSUE TITLE
OpnSense AV Proxy - Eicar links have updated again

### ISSUE THREAD

**Issue by tazboyz16** [opnsense/docs#530]
Related to this request with link changes: https://github.com/opnsense/docs/issues/206
https://docs.opnsense.org/manual/how-tos/proxyicapantivirusinternal.html

It looks like Eicar has changed their links again for the testing files
https://www.eicar.org/download-anti-malware-testfile/

**Comment by AdSchellevis** [comment]
let's try to make this the last time https://github.com/opnsense/docs/commit/a10e5962e65af467ababbd9c24d2f05dae2c8559
