### ISSUE TITLE
WireGuard: Confusing roadwarrior instructions

### ISSUE THREAD

**Issue by HritwikSinghal** [opnsense/docs#549]
- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**

on https://docs.opnsense.org/manual/how-tos/wireguard-client.html , it seems few steps have not been updated after this commit https://github.com/opnsense/docs/commit/ac586586b2ebc9a81d40a352a7f7d4ad76c89587 .

This commit Removed the 1st step and all the steps after that were changed in number. (so "step 2" became "step 1" and so-on). 
But at a few places, the changes were not made. see below.

--- 

![image](https://github.com/opnsense/docs/assets/29531474/485d445d-39f2-428d-bd70-74ae8753a07d)

![image](https://github.com/opnsense/docs/assets/29531474/a1ca148d-afd1-46ad-a4f5-6f51ff120c02)

these Hints suggests steps in 5a, before "step 5" (or "5a"). This is because "Step 5a" was renamed To "step 4a", but not in the hinds

--- 

![image](https://github.com/opnsense/docs/assets/29531474/7af9395f-ca2f-41ba-a7fe-ae3898af28eb)

Step 7 does not exist, change to step 6.

---

![image](https://github.com/opnsense/docs/assets/29531474/6772d7d3-810e-4d50-9060-a797483af149)

Repeat step 2, not 3

---

![image](https://github.com/opnsense/docs/assets/29531474/eae6ee8e-b861-4c3c-819c-652da439da76)

steps shoud be 4a and 4b, not 5a and 5b.

---

![image](https://github.com/opnsense/docs/assets/29531474/0b91a140-00eb-458a-8c2a-38c20880dbd2)

should be 4a

---

And  many more!
---

**Suggestions**

Will open a PR to fix this.
Edit: https://github.com/opnsense/docs/pull/550

**Version affected**

latest Docs Master as of Apr 5 2024

**Comment by HritwikSinghal** [comment]
this PR should fix these issues. Please review this thoroughly. 

https://github.com/opnsense/docs/pull/550

**Comment by AdSchellevis** [comment]
@HritwikSinghal thanks for offering the PR, we seem to have missed the renumbering in the text.

**Comment by HritwikSinghal** [comment]
Hey, I can still see the old version with out-of-date numbering.

**Comment by fichtner** [comment]
Maybe you have more luck on Subday? 😉

**Comment by HritwikSinghal** [comment]
> Maybe you have more luck on Sunday? 😉

ah, there must be some release pipeline to push changes to website.

**Comment by fichtner** [comment]
It‘s updated in batches. For now I think there won’t be any updates on the weekend that seem pressing.


Cheers,
Franco

**Comment by HritwikSinghal** [comment]
> It‘s updated in batches. For now I think there won’t be any updates on the weekend that seem pressing.
> 
> Cheers, Franco

makes sense. thanks for clearing that up :)

**Comment by AdSchellevis** [comment]
pushed (https://docs.opnsense.org/manual/how-tos/wireguard-client.html)
