### ISSUE TITLE
WireGuard Road Warrior Setup | Mandatory Private Key?

### ISSUE THREAD

**Issue by DLopezJr** [opnsense/docs#553]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**
- Sources:
  - https://docs.opnsense.org/manual/how-tos/wireguard-client.html
  - https://github.com/opnsense/docs/blob/master/source/manual/how-tos/wireguard-client.rst

Attempting to follow the "WireGuard Road Warrior Setup" documentation results in a lock up in step 1. 

The guide states that the "Private key" will auto-generate, but I'm running into an error. It's stating that a "A value is required." for the "Private key" field and won't let me continue. 

- The current OPNsense version where the bug first appeared
  - Not sure if the first version. 
    - ```Currently running OPNsense 24.1.5_3```
- The last OPNsense version where the bug did not exist
  - I don't know. 
- The exact URL of the GUI page involved (if any)
  - ```<domain>/ui/wireguard/general#```
- A list of steps to replicate the bug
  1. Follow guide at: https://docs.opnsense.org/manual/how-tos/wireguard-client.html
  2. Go to ```<domain>/ui/wireguard/general#``` and click the "+" button.
  3. Fill out the form according to the guide.
  4. Notice error on "Private key" field that reads: "A value is required."
  5. Press "Save" button.
  6. Realize the form can not save without a private key.

**Suggestions**

- Notate which version of OPNsense changed to requiring private key.
- Notate in documentation if using a version before the change that it is not mandatory.
- Change the error from: "A value is required." to "A value is required. Press the cogwheel to auto-generate new keys OR provide your own."

**Version affected**

Which version of the software are you using?
- ```Currently running OPNsense 24.1.5_3```

**Describe alternatives you considered**

I asked about this in the [forums](https://forum.opnsense.org/index.php?topic=39977.0#msg195883) and was told to click the cog wheel next to "Public Key" which generates a keypair. Doing this allowed me to complete step 1.

**Comment by AdSchellevis** [comment]
The current documentation should match the current version, the most practical option is likely to replace "This will initially be blank; it will be populated once the configuration is saved" with "This will initially be blank; Press the cogwheel to auto-generate new keys."
