### ISSUE TITLE
Interfaces / Other types / VLAN

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/docs#590]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Not a solid plan yet, but it might be practical to explain a bit about vlan usage and best practices like not combining tagged and untagged traffic on the same interface (as this will clutter stats and has some downsides in terms of visibility)

**Describe the solution you like**

Maybe extend the VLAN part a bit, but adding some general documentation about interfaces and common types might also be practical.

**Describe alternatives you considered**

none

**Comment by SeimusS** [comment]
It doesn't only cluster stats in many cases it can be a cause of interface errors. Have seen some examples on the forum already.

I think this is a great idea btw. A bit of more educative approach targeted for newcomers maybe? 

How deep you want to go into the VLAN rabbit hole?
Examples and best practices only or as well explanation on a more technical level? ;)

Regards,
S.
