### ISSUE TITLE
organge fr pages: images are stretched - looks awful

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/docs#69]
@fichtner please assign to the author

![screenshot_20181028_190055](https://user-images.githubusercontent.com/3713914/47619883-cc9be400-dae3-11e8-8a3e-fe772f5ad1f4.png)

**Comment by fichtner** [comment]
Not strictly the author's fault https://github.com/opnsense/docs/commit/52aa7c2b066d55912ad140ba4ec30cb87ff5a77c

**Comment by AdSchellevis** [comment]
people tend to copy.... width renders correctly in html output, scale doesn't, I've replaced all in https://github.com/opnsense/docs/commit/52aa7c2b066d55912ad140ba4ec30cb87ff5a77c, since then others seem to have entered ;(
