### ISSUE TITLE
Menu item "System > Access > Configuration" is gone

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/docs#89]
Referring to the documentation [here](https://wiki.opnsense.org/manual/users.html?highlight=radius), I am unable to find the menu entry for "System > Access > Configuration":
![image](https://user-images.githubusercontent.com/75446/49550031-bd7e3200-f8ea-11e8-95e6-fe052323c486.png)

I was looking for the described settings in other sections for quite a while but did not succeed.
I was wondering whether it might be a bug?

**Comment by jpawlowski** [comment]
I sweat I had looked for it right there 😁
Thanks, never fixed a bug so easily, he?

**Comment by AdSchellevis** [comment]
It's still a bug :)

**Comment by AdSchellevis** [comment]
We need to adjust the documentation here, let's keep this one open for now.
