### ISSUE TITLE
Hover text for service restart

### ISSUE THREAD

**Issue by soder10** [opnsense/docs#93]
Hello devs,

a note: maybe its just me, but if I see the service status any of the locations (service status on the dashboard, or System: Diagnostics: Services or the various individual services under \Services), the icon representing the "recycle" symbol can be interpreted in different ways:
1) restart of the service
2) reload of the service

1) will result complete service-interrupting restart of the service, while 2) may just reload the service configuration file, keeping the service still UP.

I figured it out the actual performed action is indeed 1) but that may not be that obvious for any new user. Do you think some hover message when pointing to the icon with mouse should clearly say: "Restart service" to signal it wont be just a non-interrupting "Reload config" ?

The reason why I mentioned this issue under DOCS is that I couldnt find any page that describes the "services" section, where it could be clearly mentioned that the recycle symbol does service-interrupting restart and not config reload.

Thanks!

**Comment by soder10** [comment]
Ps: there seems to be a bug in this github engine:
the text I wrote in the opening post after 1) and 2)  says this: "1) will result complete service-interrupting restart..."
It is indeed confirmed when I edit the text, I get the correct editable content inside the textbox.

While the rendered HTML page shows:

3. will result complete service-interrupting restart

**Comment by soder10** [comment]
Anyone agrees / disagrees with my idea?

**Comment by mimugmail** [comment]
I think every service only restarts and not reloads. HAProxy plugin has a graceful restart feature, but most services are restarted by default.

**Comment by fichtner** [comment]
It depends on the service and its internal implementation.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)

**Comment by soder10** [comment]
So what should I do?

**Comment by AdSchellevis** [comment]
@soder10 I'm not sure where it should fit in properly, but a PR with a suggestion would be a very good starting point.
