### ISSUE TITLE
Feature request: show the location of logfiles in GUI

### ISSUE THREAD

**Issue by soder10** [opnsense/docs#97]
Hello devs,
I was trying to locate the logfile for pf in the filesystem, but was unable to find. That was when I realised, there is no hint in the GUI, from which log the GUI data is coming from. I think it would make sense to reveal the path to the file that is being presented in the various GUI logging related menus. So if one wants to read these logs directly from CLI, there will be specific info which logfile needs to be opened.

**Comment by fichtner** [comment]
Done via https://github.com/opnsense/docs/commit/9191019ce6c8dcea4c4991189f4f08091635f722
